// Auto-generated by scratchpad/gen_small_logos.py — station-list logos
// pre-scaled to fit 138x38 so list rows render at 1:1 (no sw transform:
// LVGL's transform path starved the decoder in Phase 13 and wedged the
// LVGL task in Phase 17 — nothing in the UI may scale images at runtime).
#include "lvgl.h"

extern const uint8_t logo_s_TBS_bin_start[] asm("_binary_logo_s_TBS_bin_start");
extern const uint8_t logo_s_QRR_bin_start[] asm("_binary_logo_s_QRR_bin_start");
extern const uint8_t logo_s_LFR_bin_start[] asm("_binary_logo_s_LFR_bin_start");
extern const uint8_t logo_s_RN1_bin_start[] asm("_binary_logo_s_RN1_bin_start");
extern const uint8_t logo_s_RN2_bin_start[] asm("_binary_logo_s_RN2_bin_start");
extern const uint8_t logo_s_INT_bin_start[] asm("_binary_logo_s_INT_bin_start");
extern const uint8_t logo_s_FMT_bin_start[] asm("_binary_logo_s_FMT_bin_start");
extern const uint8_t logo_s_FMJ_bin_start[] asm("_binary_logo_s_FMJ_bin_start");
extern const uint8_t logo_s_JORF_bin_start[] asm("_binary_logo_s_JORF_bin_start");
extern const uint8_t logo_s_BAYFM78_bin_start[] asm("_binary_logo_s_BAYFM78_bin_start");
extern const uint8_t logo_s_NACK5_bin_start[] asm("_binary_logo_s_NACK5_bin_start");
extern const uint8_t logo_s_YFM_bin_start[] asm("_binary_logo_s_YFM_bin_start");
extern const uint8_t logo_s_IBS_bin_start[] asm("_binary_logo_s_IBS_bin_start");
extern const uint8_t logo_s_JOAK_bin_start[] asm("_binary_logo_s_JOAK_bin_start");
extern const uint8_t logo_s_JOAK_FM_bin_start[] asm("_binary_logo_s_JOAK_FM_bin_start");

static const lv_image_dsc_t logo_s_TBS = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 125, .h = 38, .stride = 250 },
    .data = logo_s_TBS_bin_start, .data_size = 9500,
};
static const lv_image_dsc_t logo_s_QRR = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 132, .h = 38, .stride = 264 },
    .data = logo_s_QRR_bin_start, .data_size = 10032,
};
static const lv_image_dsc_t logo_s_LFR = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 126, .h = 38, .stride = 252 },
    .data = logo_s_LFR_bin_start, .data_size = 9576,
};
static const lv_image_dsc_t logo_s_RN1 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 138, .h = 20, .stride = 276 },
    .data = logo_s_RN1_bin_start, .data_size = 5520,
};
static const lv_image_dsc_t logo_s_RN2 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 104, .h = 38, .stride = 208 },
    .data = logo_s_RN2_bin_start, .data_size = 7904,
};
static const lv_image_dsc_t logo_s_INT = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 91, .h = 38, .stride = 182 },
    .data = logo_s_INT_bin_start, .data_size = 6916,
};
static const lv_image_dsc_t logo_s_FMT = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 94, .h = 38, .stride = 188 },
    .data = logo_s_FMT_bin_start, .data_size = 7144,
};
static const lv_image_dsc_t logo_s_FMJ = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 91, .h = 38, .stride = 182 },
    .data = logo_s_FMJ_bin_start, .data_size = 6916,
};
static const lv_image_dsc_t logo_s_JORF = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 138, .h = 37, .stride = 276 },
    .data = logo_s_JORF_bin_start, .data_size = 10212,
};
static const lv_image_dsc_t logo_s_BAYFM78 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 138, .h = 35, .stride = 276 },
    .data = logo_s_BAYFM78_bin_start, .data_size = 9660,
};
static const lv_image_dsc_t logo_s_NACK5 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 65, .h = 38, .stride = 130 },
    .data = logo_s_NACK5_bin_start, .data_size = 4940,
};
static const lv_image_dsc_t logo_s_YFM = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 117, .h = 38, .stride = 234 },
    .data = logo_s_YFM_bin_start, .data_size = 8892,
};
static const lv_image_dsc_t logo_s_IBS = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 73, .h = 38, .stride = 146 },
    .data = logo_s_IBS_bin_start, .data_size = 5548,
};
static const lv_image_dsc_t logo_s_JOAK = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 99, .h = 38, .stride = 198 },
    .data = logo_s_JOAK_bin_start, .data_size = 7524,
};
static const lv_image_dsc_t logo_s_JOAK_FM = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 99, .h = 38, .stride = 198 },
    .data = logo_s_JOAK_FM_bin_start, .data_size = 7524,
};

const lv_image_dsc_t *const STATION_LOGOS_SMALL[] = {
    &logo_s_TBS, &logo_s_QRR, &logo_s_LFR, &logo_s_RN1, &logo_s_RN2, &logo_s_INT, &logo_s_FMT, &logo_s_FMJ, &logo_s_JORF, &logo_s_BAYFM78, &logo_s_NACK5, &logo_s_YFM, &logo_s_IBS, &logo_s_JOAK, &logo_s_JOAK_FM,
};
