// Auto-generated by scratchpad/gen_logos.py. Pixel data is embedded
// as raw RGB565 binaries via EMBED_FILES; this only wraps them.
#include "lvgl.h"

extern const uint8_t logo_TBS_bin_start[] asm("_binary_logo_TBS_bin_start");
extern const uint8_t logo_QRR_bin_start[] asm("_binary_logo_QRR_bin_start");
extern const uint8_t logo_LFR_bin_start[] asm("_binary_logo_LFR_bin_start");
extern const uint8_t logo_RN1_bin_start[] asm("_binary_logo_RN1_bin_start");
extern const uint8_t logo_RN2_bin_start[] asm("_binary_logo_RN2_bin_start");
extern const uint8_t logo_INT_bin_start[] asm("_binary_logo_INT_bin_start");
extern const uint8_t logo_FMT_bin_start[] asm("_binary_logo_FMT_bin_start");
extern const uint8_t logo_FMJ_bin_start[] asm("_binary_logo_FMJ_bin_start");
extern const uint8_t logo_JORF_bin_start[] asm("_binary_logo_JORF_bin_start");
extern const uint8_t logo_BAYFM78_bin_start[] asm("_binary_logo_BAYFM78_bin_start");
extern const uint8_t logo_NACK5_bin_start[] asm("_binary_logo_NACK5_bin_start");
extern const uint8_t logo_YFM_bin_start[] asm("_binary_logo_YFM_bin_start");
extern const uint8_t logo_IBS_bin_start[] asm("_binary_logo_IBS_bin_start");
extern const uint8_t logo_JOAK_bin_start[] asm("_binary_logo_JOAK_bin_start");
extern const uint8_t logo_JOAK_FM_bin_start[] asm("_binary_logo_JOAK_FM_bin_start");

static const lv_image_dsc_t logo_TBS = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 33, .stride = 216 },
    .data = logo_TBS_bin_start, .data_size = 7128,
};
static const lv_image_dsc_t logo_QRR = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 31, .stride = 216 },
    .data = logo_QRR_bin_start, .data_size = 6696,
};
static const lv_image_dsc_t logo_LFR = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 33, .stride = 216 },
    .data = logo_LFR_bin_start, .data_size = 7128,
};
static const lv_image_dsc_t logo_RN1 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 16, .stride = 216 },
    .data = logo_RN1_bin_start, .data_size = 3456,
};
static const lv_image_dsc_t logo_RN2 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 40, .stride = 216 },
    .data = logo_RN2_bin_start, .data_size = 8640,
};
static const lv_image_dsc_t logo_INT = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 101, .h = 42, .stride = 202 },
    .data = logo_INT_bin_start, .data_size = 8484,
};
static const lv_image_dsc_t logo_FMT = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 104, .h = 42, .stride = 208 },
    .data = logo_FMT_bin_start, .data_size = 8736,
};
static const lv_image_dsc_t logo_FMJ = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 101, .h = 42, .stride = 202 },
    .data = logo_FMJ_bin_start, .data_size = 8484,
};
static const lv_image_dsc_t logo_JORF = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 29, .stride = 216 },
    .data = logo_JORF_bin_start, .data_size = 6264,
};
static const lv_image_dsc_t logo_BAYFM78 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 28, .stride = 216 },
    .data = logo_BAYFM78_bin_start, .data_size = 6048,
};
static const lv_image_dsc_t logo_NACK5 = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 72, .h = 42, .stride = 144 },
    .data = logo_NACK5_bin_start, .data_size = 6048,
};
static const lv_image_dsc_t logo_YFM = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 35, .stride = 216 },
    .data = logo_YFM_bin_start, .data_size = 7560,
};
static const lv_image_dsc_t logo_IBS = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 81, .h = 42, .stride = 162 },
    .data = logo_IBS_bin_start, .data_size = 6804,
};
static const lv_image_dsc_t logo_JOAK = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 41, .stride = 216 },
    .data = logo_JOAK_bin_start, .data_size = 8856,
};
static const lv_image_dsc_t logo_JOAK_FM = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 108, .h = 41, .stride = 216 },
    .data = logo_JOAK_FM_bin_start, .data_size = 8856,
};

const lv_image_dsc_t *const STATION_LOGOS[] = {
    &logo_TBS, &logo_QRR, &logo_LFR, &logo_RN1, &logo_RN2, &logo_INT, &logo_FMT, &logo_FMJ, &logo_JORF, &logo_BAYFM78, &logo_NACK5, &logo_YFM, &logo_IBS, &logo_JOAK, &logo_JOAK_FM,
};
