// Auto-generated by tools/gen_splash.py from splash.png.webp.
// Boot splash, pre-composited on the UI background (C_BG) and pre-scaled to
// 300x118 — blitted 1:1 like every other image (no runtime transforms).
#include "lvgl.h"

extern const uint8_t splash_bin_start[] asm("_binary_splash_bin_start");

const lv_image_dsc_t SPLASH_IMG = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = 300, .h = 118, .stride = 600 },
    .data = splash_bin_start, .data_size = 70800,
};
