#!/usr/bin/env python3
"""Phase 30 multi-area asset pipeline.

Builds the nationwide station database + a packed logo blob for the data
partition, so the board can browse any Radiko area fully offline:

  - fetch every station across JP1..JP47 (id, name, area membership),
  - download each logo, downscale to BIG (player, fit 300x56, on white) and
    SMALL (list, fit 138x38, on the dark row bg), as RGB565-LE,
  - pack all pixels into logos.bin (flashed to the `logos` partition),
  - emit stations_gen.c: the station table + the logo index (offset/dims),
    consumed by the stations component.

Run: tools/venv has Pillow. `python tools/gen_stationdb.py`
"""
import json
import os
import re
import struct
import urllib.request

from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT_C = os.path.join(ROOT, "idf", "components", "stations", "stations_gen.c")
OUT_BIN = os.path.join(ROOT, "idf", "components", "stations", "logos.bin")

BIG = (300, 56)
SMALL = (138, 38)
WHITE = (255, 255, 255)
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".logo_cache")

def fetch_stations():
    st = {}
    for n in range(1, 48):
        url = "http://radiko.jp/v3/station/list/JP%d.xml" % n
        xml = urllib.request.urlopen(url, timeout=20).read().decode("utf-8")
        for blk in re.findall(r"<station>.*?</station>", xml, re.S):
            sid = re.search(r"<id>([^<]+)</id>", blk).group(1)
            name = re.search(r"<name>([^<]+)</name>", blk).group(1)
            logos = re.findall(r"<logo[^>]*>([^<]+)</logo>", blk)
            big = ([u for u in logos if "688x160" in u]
                   or [u for u in logos if "448x200" in u] or logos)
            d = st.setdefault(sid, {"name": name, "logo": big[0] if big else "",
                                    "areas": []})
            d["areas"].append(n)
    return st

def to_rgb565(img):
    out = bytearray()
    for r, g, b in img.getdata():
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out += struct.pack("<H", v)
    return bytes(out)

def render(src, box, bg):
    scale = min(box[0] / src.width, box[1] / src.height, 1.0)
    w, h = max(1, round(src.width * scale)), max(1, round(src.height * scale))
    im = src.resize((w, h), Image.LANCZOS)
    canvas = Image.new("RGBA", (w, h), bg + (255,))
    canvas.alpha_composite(im)
    return canvas.convert("RGB"), w, h

def main():
    st = fetch_stations()
    ids = sorted(st.keys())
    print("stations:", len(ids))

    os.makedirs(CACHE, exist_ok=True)
    blob = bytearray()
    index = []   # (id, name, area_mask, big_off,big_w,big_h, sm_off,sm_w,sm_h)
    import io
    for sid in ids:
        s = st[sid]
        cf = os.path.join(CACHE, sid + ".png")
        if os.path.exists(cf):
            raw = open(cf, "rb").read()
        else:
            raw = urllib.request.urlopen(s["logo"], timeout=20).read()
            open(cf, "wb").write(raw)
        src = Image.open(io.BytesIO(raw)).convert("RGBA")
        # Both sizes on WHITE: the player card is white, and dark logos need a
        # light background to be visible on the dark list rows too.
        big_img, bw, bh = render(src, BIG, WHITE)
        sm_img, sw, sh = render(src, SMALL, WHITE)
        big_off = len(blob); blob += to_rgb565(big_img)
        sm_off = len(blob);  blob += to_rgb565(sm_img)
        mask = 0
        for a in s["areas"]:
            mask |= (1 << (a - 1))   # JP1 -> bit0 .. JP47 -> bit46
        index.append((sid, s["name"], mask, big_off, bw, bh, sm_off, sw, sh))
        print(" %-10s %2d areas  big %dx%d  small %dx%d" % (sid, len(s["areas"]), bw, bh, sw, sh))

    open(OUT_BIN, "wb").write(blob)
    print("logos.bin:", len(blob), "bytes (%.2f MB)" % (len(blob) / 1048576))

    with open(OUT_C, "w") as f:
        f.write('// Auto-generated by tools/gen_stationdb.py — nationwide Radiko\n')
        f.write('// station database + logo index. Pixels live in the `logos`\n')
        f.write('// data partition (logos.bin), mmap\'d at runtime. Do not edit.\n')
        f.write('#include "stations.h"\n\n')
        f.write("const station_t STATIONS_ALL[] = {\n")
        for sid, name, mask, bo, bw, bh, so, sw, sh in index:
            nm = name.encode("utf-8").decode("unicode_escape") if False else name
            f.write('    { "%s", "%s", 0x%016XULL, %d,%d,%d, %d,%d,%d },\n'
                    % (sid, nm.replace('"', '\\"'), mask, bo, bw, bh, so, sw, sh))
        f.write("};\n")
        f.write("const int STATIONS_ALL_COUNT = %d;\n" % len(index))
    print("wrote", OUT_C)

if __name__ == "__main__":
    main()
