#!/usr/bin/env python3
"""Generate pre-scaled station-list logos (fit 138x38) from the existing
300x56-fit RGB565 bins, so LVGL never runs a software transform at runtime
(the sw-transform path both starved the decoder in Phase 13 and wedged the
LVGL task in Phase 17). Box-filter downscale, RGB565 little-endian in/out.

Reads logos_gen.c for the name/w/h table, writes logo_s_<NAME>.bin and
logos_small_gen.c into the logos component.
"""
import re, struct, os

COMP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "idf", "components", "logos")
FIT_W, FIT_H = 138, 38

src = open(os.path.join(COMP, "logos_gen.c")).read()

# name -> (w, h), in file order
entries = re.findall(
    r"static const lv_image_dsc_t logo_(\w+) = \{.*?\.w = (\d+), \.h = (\d+)",
    src, re.S)
order = re.search(r"STATION_LOGOS\[\] = \{\s*(.*?)\s*,?\s*\};", src, re.S).group(1)
order = [n.strip().lstrip("&").replace("logo_", "") for n in order.split(",") if n.strip()]

def rgb565_to_rgb(p):
    r = (p >> 11) & 0x1F
    g = (p >> 5) & 0x3F
    b = p & 0x1F
    return (r << 3 | r >> 2, g << 2 | g >> 4, b << 3 | b >> 2)

def rgb_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def box_downscale(px, w, h, nw, nh):
    out = []
    for oy in range(nh):
        y0, y1 = oy * h // nh, max(oy * h // nh + 1, (oy + 1) * h // nh)
        for ox in range(nw):
            x0, x1 = ox * w // nw, max(ox * w // nw + 1, (ox + 1) * w // nw)
            rs = gs = bs = n = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    r, g, b = rgb565_to_rgb(px[y * w + x])
                    rs += r; gs += g; bs += b; n += 1
            out.append(rgb_to_rgb565(rs // n, gs // n, bs // n))
    return out

dims = {n: (int(w), int(h)) for n, w, h in entries}
descs = []
for name in order:
    w, h = dims[name]
    raw = open(os.path.join(COMP, f"logo_{name}.bin"), "rb").read()
    px = list(struct.unpack(f"<{w*h}H", raw))
    scale = min(FIT_W / w, FIT_H / h, 1.0)
    nw, nh = max(1, round(w * scale)), max(1, round(h * scale))
    spx = box_downscale(px, w, h, nw, nh) if scale < 1.0 else px
    out = struct.pack(f"<{nw*nh}H", *spx)
    with open(os.path.join(COMP, f"logo_s_{name}.bin"), "wb") as f:
        f.write(out)
    descs.append((name, nw, nh, len(out)))
    print(f"{name}: {w}x{h} -> {nw}x{nh} ({len(out)} bytes)")

lines = ["// Auto-generated by scratchpad/gen_small_logos.py — station-list logos",
         "// pre-scaled to fit 138x38 so list rows render at 1:1 (no sw transform:",
         "// LVGL's transform path starved the decoder in Phase 13 and wedged the",
         "// LVGL task in Phase 17 — nothing in the UI may scale images at runtime).",
         '#include "lvgl.h"', ""]
for n, _, _, _ in descs:
    lines.append(f'extern const uint8_t logo_s_{n}_bin_start[] asm("_binary_logo_s_{n}_bin_start");')
lines.append("")
for n, w, h, size in descs:
    lines += [f"static const lv_image_dsc_t logo_s_{n} = {{",
              f"    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,",
              f"                 .w = {w}, .h = {h}, .stride = {w*2} }},",
              f"    .data = logo_s_{n}_bin_start, .data_size = {size},",
              "};"]
lines.append("")
lines.append("const lv_image_dsc_t *const STATION_LOGOS_SMALL[] = {")
lines.append("    " + ", ".join(f"&logo_s_{n}" for n, _, _, _ in descs) + ",")
lines.append("};")
open(os.path.join(COMP, "logos_small_gen.c"), "w").write("\n".join(lines) + "\n")
print("wrote logos_small_gen.c")
