#!/usr/bin/env python3
"""Generate the boot splash asset from assets/splash.png.webp.

Composites the transparent logo onto the UI background colour (C_BG 0x1A1A2E),
scales to fit 300 px wide, and emits RGB565-LE splash.bin + splash_gen.c into
the logos component (embedded via the existing *.bin GLOB). Requires Pillow.
"""
import os
import struct
import sys

from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "assets", "splash.png.webp")
COMP = os.path.join(ROOT, "idf", "components", "logos")
FIT_W = 300
C_BG = (0x1A, 0x1A, 0x2E)

img = Image.open(SRC).convert("RGBA")
scale = FIT_W / img.width
w, h = FIT_W, max(1, round(img.height * scale))
img = img.resize((w, h), Image.LANCZOS)

bg = Image.new("RGBA", (w, h), C_BG + (255,))
bg.alpha_composite(img)
rgb = bg.convert("RGB")

px = []
for r, g, b in rgb.getdata():
    px.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
data = struct.pack(f"<{w*h}H", *px)

with open(os.path.join(COMP, "splash.bin"), "wb") as f:
    f.write(data)

gen = f"""// Auto-generated by tools/gen_splash.py from assets/splash.png.webp.
// Boot splash, pre-composited on the UI background (C_BG) and pre-scaled to
// {w}x{h} — blitted 1:1 like every other image (no runtime transforms).
#include "lvgl.h"

extern const uint8_t splash_bin_start[] asm("_binary_splash_bin_start");

const lv_image_dsc_t SPLASH_IMG = {{
    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,
                 .w = {w}, .h = {h}, .stride = {w*2} }},
    .data = splash_bin_start, .data_size = {len(data)},
}};
"""
with open(os.path.join(COMP, "splash_gen.c"), "w") as f:
    f.write(gen)
print(f"splash: {w}x{h}, {len(data)} bytes")
